export const PROCESSING = {
  MAX_PREVIEW_DIMENSION: 1280,
  DEBOUNCE_MS: 350,
  QUICK_PREVIEW_DENSITY_MIN: 20,
  QUICK_PREVIEW_DENSITY_MAX: 30,
} as const;

export const EXPORT = {
  VIDEO_FPS: 30,
  VIDEO_BITRATE: 8_000_000,
  RECORDER_TIMESLICE_MS: 200,
  FRAME_DECODE_WAIT_MS: 50,
  FRAME_PACE_DELAY_MS: 33,
  FINAL_FLUSH_DELAY_MS: 250,
} as const;

export const LIMITS = {
  MAX_FILE_SIZE_MB: 500,
  BROWSER_MEMORY_LIMIT_GB: 2,
} as const;


